[2025-04-22T23:50:41.510+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T23:50:41.528+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestao-blobstorage-azure.ingestao_azure-2446 manual__2025-04-22T23:50:39.827742+00:00 [queued]>
[2025-04-22T23:50:41.538+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestao-blobstorage-azure.ingestao_azure-2446 manual__2025-04-22T23:50:39.827742+00:00 [queued]>
[2025-04-22T23:50:41.541+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-22T23:50:41.557+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingestao_azure-2446> on 2025-04-22 23:50:39.827742+00:00
[2025-04-22T23:50:41.564+0000] {standard_task_runner.py:72} INFO - Started process 2152 to run task
[2025-04-22T23:50:41.569+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ingestao-blobstorage-azure', 'ingestao_azure-2446', 'manual__2025-04-22T23:50:39.827742+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/ingestao-blobstorage-azure.py', '--cfg-path', '/tmp/tmp_tvz_8wi']
[2025-04-22T23:50:41.572+0000] {standard_task_runner.py:105} INFO - Job 67: Subtask ingestao_azure-2446
[2025-04-22T23:50:41.631+0000] {task_command.py:467} INFO - Running <TaskInstance: ingestao-blobstorage-azure.ingestao_azure-2446 manual__2025-04-22T23:50:39.827742+00:00 [running]> on host e50052774237
[2025-04-22T23:50:41.724+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestao-blobstorage-azure' AIRFLOW_CTX_TASK_ID='ingestao_azure-2446' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T23:50:39.827742+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T23:50:39.827742+00:00'
[2025-04-22T23:50:41.726+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-22T23:50:42.455+0000] {_universal.py:506} INFO - Request URL: 'https://rpeottaprojeto.blob.core.windows.net/brasfels-2446/LD-2446-PE-CAR-PLN-GRC-001-R0.xlsx'
Request method: 'PUT'
Request headers:
    'Content-Length': '4187310'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.24.1 Python/3.10.16 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '99ee4862-1fd4-11f0-a80b-9e5d745be2f1'
    'Authorization': 'REDACTED'
A body is sent with the request
[2025-04-22T23:50:49.769+0000] {_universal.py:545} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 22 Apr 2025 23:50:49 GMT'
    'ETag': '"0x8DD81F8825FC55A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fabcb91f-801e-006b-58e1-b3953f000000'
    'x-ms-client-request-id': '99ee4862-1fd4-11f0-a80b-9e5d745be2f1'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 22 Apr 2025 23:50:48 GMT'
[2025-04-22T23:50:49.773+0000] {logging_mixin.py:190} INFO - Arquivo 'LD-2446-PE-CAR-PLN-GRC-001-R0.xlsx' enviado com sucesso para o container 'brasfels-2446'.
[2025-04-22T23:50:50.176+0000] {_universal.py:506} INFO - Request URL: 'https://rpeottaprojeto.blob.core.windows.net/brasfels-2446/CS-2446-PE-CAR-PLN-GRC-001-R0.xlsx'
Request method: 'PUT'
Request headers:
    'Content-Length': '80279'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.24.1 Python/3.10.16 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9e8879ec-1fd4-11f0-a80b-9e5d745be2f1'
    'Authorization': 'REDACTED'
A body is sent with the request
[2025-04-22T23:50:51.680+0000] {_universal.py:545} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 22 Apr 2025 23:50:51 GMT'
    'ETag': '"0x8DD81F88386CC92"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'c646f2be-b01e-0060-60e1-b36e54000000'
    'x-ms-client-request-id': '9e8879ec-1fd4-11f0-a80b-9e5d745be2f1'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 22 Apr 2025 23:50:51 GMT'
[2025-04-22T23:50:51.683+0000] {logging_mixin.py:190} INFO - Arquivo 'CS-2446-PE-CAR-PLN-GRC-001-R0.xlsx' enviado com sucesso para o container 'brasfels-2446'.
[2025-04-22T23:50:51.695+0000] {logging_mixin.py:190} INFO - Erro ao enviar o arquivo 'faturamento_2446.xlsx': [Errno 2] No such file or directory: '/opt/***/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/CONTROLES (POWER BI)/240124/BRASFELLS/faturamento_2446.xlsx'
[2025-04-22T23:50:51.716+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 45, in upload_files_brasfels
    upload_to_blob(
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 25, in upload_to_blob
    raise e
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 18, in upload_to_blob
    with open(local_file_path, "rb") as data:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/CONTROLES (POWER BI)/240124/BRASFELLS/faturamento_2446.xlsx'
[2025-04-22T23:50:51.769+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=ingestao-blobstorage-azure, task_id=ingestao_azure-2446, run_id=manual__2025-04-22T23:50:39.827742+00:00, execution_date=20250422T235039, start_date=20250422T235041, end_date=20250422T235051
[2025-04-22T23:50:51.809+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-22T23:50:51.816+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 67 for task ingestao_azure-2446 ([Errno 2] No such file or directory: '/opt/airflow/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/CONTROLES (POWER BI)/240124/BRASFELLS/faturamento_2446.xlsx'; 2152)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 45, in upload_files_brasfels
    upload_to_blob(
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 25, in upload_to_blob
    raise e
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 18, in upload_to_blob
    with open(local_file_path, "rb") as data:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/CONTROLES (POWER BI)/240124/BRASFELLS/faturamento_2446.xlsx'
[2025-04-22T23:50:51.857+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-22T23:50:51.880+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T23:50:51.885+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
