[2025-04-22T23:56:40.037+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T23:56:40.054+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestao-blobstorage-azure.ingestao_azure-2446 manual__2025-04-22T23:56:14.360769+00:00 [queued]>
[2025-04-22T23:56:40.064+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestao-blobstorage-azure.ingestao_azure-2446 manual__2025-04-22T23:56:14.360769+00:00 [queued]>
[2025-04-22T23:56:40.066+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-22T23:56:40.081+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingestao_azure-2446> on 2025-04-22 23:56:14.360769+00:00
[2025-04-22T23:56:40.088+0000] {standard_task_runner.py:72} INFO - Started process 2257 to run task
[2025-04-22T23:56:40.092+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ingestao-blobstorage-azure', 'ingestao_azure-2446', 'manual__2025-04-22T23:56:14.360769+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/ingestao-blobstorage-azure.py', '--cfg-path', '/tmp/tmpp6qz1mf_']
[2025-04-22T23:56:40.095+0000] {standard_task_runner.py:105} INFO - Job 75: Subtask ingestao_azure-2446
[2025-04-22T23:56:40.154+0000] {task_command.py:467} INFO - Running <TaskInstance: ingestao-blobstorage-azure.ingestao_azure-2446 manual__2025-04-22T23:56:14.360769+00:00 [running]> on host e50052774237
[2025-04-22T23:56:40.243+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestao-blobstorage-azure' AIRFLOW_CTX_TASK_ID='ingestao_azure-2446' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T23:56:14.360769+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T23:56:14.360769+00:00'
[2025-04-22T23:56:40.245+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-22T23:56:40.808+0000] {_universal.py:506} INFO - Request URL: 'https://rpeottaprojeto.blob.core.windows.net/brasfels-2446/LD-2446-PE-CAR-PLN-GRC-001-R0.xlsx'
Request method: 'PUT'
Request headers:
    'Content-Length': '4187310'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.24.1 Python/3.10.16 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6f86aff0-1fd5-11f0-bd18-9e5d745be2f1'
    'Authorization': 'REDACTED'
A body is sent with the request
[2025-04-22T23:56:43.951+0000] {_universal.py:545} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 22 Apr 2025 23:56:43 GMT'
    'ETag': '"0x8DD81F9558CA7B6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ebffc6c1-801e-0019-2fe2-b39270000000'
    'x-ms-client-request-id': '6f86aff0-1fd5-11f0-bd18-9e5d745be2f1'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 22 Apr 2025 23:56:43 GMT'
[2025-04-22T23:56:43.955+0000] {logging_mixin.py:190} INFO - Arquivo 'LD-2446-PE-CAR-PLN-GRC-001-R0.xlsx' enviado com sucesso para o container 'brasfels-2446'.
[2025-04-22T23:56:44.226+0000] {_universal.py:506} INFO - Request URL: 'https://rpeottaprojeto.blob.core.windows.net/brasfels-2446/CS-2446-PE-CAR-PLN-GRC-001-R0.xlsx'
Request method: 'PUT'
Request headers:
    'Content-Length': '80279'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.24.1 Python/3.10.16 (Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '71901bc4-1fd5-11f0-bd18-9e5d745be2f1'
    'Authorization': 'REDACTED'
A body is sent with the request
[2025-04-22T23:56:45.602+0000] {_universal.py:545} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 22 Apr 2025 23:56:45 GMT'
    'ETag': '"0x8DD81F95684703B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '5443d945-201e-003f-44e2-b3da68000000'
    'x-ms-client-request-id': '71901bc4-1fd5-11f0-bd18-9e5d745be2f1'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 22 Apr 2025 23:56:44 GMT'
[2025-04-22T23:56:45.605+0000] {logging_mixin.py:190} INFO - Arquivo 'CS-2446-PE-CAR-PLN-GRC-001-R0.xlsx' enviado com sucesso para o container 'brasfels-2446'.
[2025-04-22T23:56:45.621+0000] {logging_mixin.py:190} INFO - Erro ao enviar o arquivo 'PAR_2446_BRASFELS_R0.xlsx': [Errno 2] No such file or directory: '/opt/***/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/PAR/PAR_2446_BRASFELS_R0.xlsx'
[2025-04-22T23:56:45.624+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 45, in upload_files_brasfels
    upload_to_blob(
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 25, in upload_to_blob
    raise e
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 18, in upload_to_blob
    with open(local_file_path, "rb") as data:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/PAR/PAR_2446_BRASFELS_R0.xlsx'
[2025-04-22T23:56:45.642+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=ingestao-blobstorage-azure, task_id=ingestao_azure-2446, run_id=manual__2025-04-22T23:56:14.360769+00:00, execution_date=20250422T235614, start_date=20250422T235640, end_date=20250422T235645
[2025-04-22T23:56:45.672+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-22T23:56:45.674+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 75 for task ingestao_azure-2446 ([Errno 2] No such file or directory: '/opt/airflow/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/PAR/PAR_2446_BRASFELS_R0.xlsx'; 2257)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 45, in upload_files_brasfels
    upload_to_blob(
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 25, in upload_to_blob
    raise e
  File "/opt/airflow/dags/ingestao-blobstorage-azure.py", line 18, in upload_to_blob
    with open(local_file_path, "rb") as data:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dados/02. PLN_Operacional/01 - PLANEJAMENTO E CONTROLE/COORDENACAO/PAR/PAR_2446_BRASFELS_R0.xlsx'
[2025-04-22T23:56:45.688+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-22T23:56:45.704+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T23:56:45.709+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
